In [1]:
import sys
from pathlib import Path

# Ajusta o path para a pasta src (projeto/notebooks -> projeto/src)
sys.path.append(str((Path.cwd().parent / "src").resolve()))

from _01_list_extract import list_extract
from _02_discourses_extract import discourses_extract
from _03_discourse_preprocessing import preprocessing
from _04_embeddings import generate_discourse_embeddings
# from _04_topics import topics_main
# from _05_llm_analysis import llm_analysis

import pandas as pd
from gensim.models import LdaModel

import os
import shutil

In [ ]:
# teste de extração
# list_extract("02/07/2022", "05/07/2022")

.....................................
... Função list_extract iniciada! ...
... URL base:  https://www.camara.leg.br/internet/sitaqweb/resultadoPesquisaDiscursos.asp?txIndexacao=&CurrentPage=1&BasePesq=plenario&txOrador=&txPartido=&dtInicio=02/07/2022&dtFim=05/07/2022&txUF=&txSessao=&listaTipoSessao=&listaTipoInterv=&inFalaPres=&listaTipoFala=&listaFaseSessao=&txAparteante=&listaEtapa=&CampoOrdenacao=dtSessao&TipoOrdenacao=DESC&PageSize=550&txTexto=&txSumario= ...
... Acessando página! ...
... Status: 200 ...
... Sucesso!!! ...
... O número total de discursos encontrados é: 158 ...
... O número total de páginas é: 1 ...
... Formatando dados extraídos! ...
... Salvando as informações! ...
... Função list_extract encerrada! ...
......................................

(           parlamentar    partido uf_partido      sessao                 fase  \
 0            LUIZ LIMA         PL         RJ    105.2022         ENCERRAMENTO
 1      ALENCAR SANTANA         PT         SP    105.2022  BREVES COMUNICAÇÕES
 2       NEUCIMAR FRAGA         PP         ES    105.2022  BREVES COMUNICAÇÕES
 3       CARMEN ZANOTTO  CIDADANIA         SC    105.2022  BREVES COMUNICAÇÕES
 4    BENEDITA DA SILVA         PT         RJ    105.2022  BREVES COMUNICAÇÕES
 ..                 ...        ...        ...         ...                  ...
 153    AFONSO FLORENCE         PT         BA  021.4.56.N         ORDEM DO DIA
 154    AFONSO FLORENCE         PT         BA  021.4.56.N         ORDEM DO DIA
 155    AFONSO FLORENCE         PT         BA  021.4.56.N         ORDEM DO DIA
 156    AFONSO FLORENCE         PT         BA  021.4.56.N         ORDEM DO DIA
 157    AFONSO FLORENCE         PT         BA  021.4.56.N         ORDEM DO DIA

            data   hora               publicacao  \
 0    05/07/2022  13h52    DCD06/07/2022 PAG. 67
 1    05/07/2022  13h44    DCD06/07/2022 PAG. 66
 2    05/07/2022  13h40    DCD06/07/2022 PAG. 65
 3    05/07/2022  13h36    DCD06/07/2022 PAG. 64
 4    05/07/2022  13h32    DCD06/07/2022 PAG. 63
 ..          ...    ...                      ...
 153  05/07/2022  15h26   DCN 07/07/2022 PAG. 49
 154  05/07/2022  15h26   DCN 07/07/2022 PAG. 29
 155  05/07/2022  15h26   DCN 07/07/2022 PAG. 21
 156  05/07/2022  15h26   DCN 07/07/2022 PAG. 13
 157  05/07/2022  15h26  DCN 07/07/2022 PAG. 103

                                          link_discurso  \
 0    https://www.camara.leg.br/internet/sitaqweb/Te...
 1    https://www.camara.leg.br/internet/sitaqweb/Te...
 2    https://www.camara.leg.br/internet/sitaqweb/Te...
 3    https://www.camara.leg.br/internet/sitaqweb/Te...
 4    https://www.camara.leg.br/internet/sitaqweb/Te...
 ..                                                 ...
 153  https://www.camara.leg.br/internet/sitaqweb/Te...
 154  https://www.camara.leg.br/internet/sitaqweb/Te...
 155  https://www.camara.leg.br/internet/sitaqweb/Te...
 156  https://www.camara.leg.br/internet/sitaqweb/Te...
 157  https://www.camara.leg.br/internet/sitaqweb/Te...

                                                sumario
 0           Redução dos índices de desemprego no País.
 1    Falta de interesse da base governista no debat...
 2    Apoio à convocação do operador do mensalão do ...
 3    Transcurso do 90º aniversário de fundação da A...
 4    Presença do ex-Presidente Luiz Inácio Lula da ...
 ..                                                 ...
 153  Adesão do orador a acordo para votação de veto...
 154  Proposta à Liderança do Governo de realização ...
 155  Defesa da rejeição do Veto Total nº 18, de 202...
 156  Votos de pesar por famílias enlutadas. Possibi...
 157  Orientação de bancada na votação do requerimen...

 [158 rows x 10 columns],
 'discursos01LISTA_158 discursos_ini 02072022_fim 05072022_pagesize 550_consulta 20260406 1929.csv')

In [ ]:
# discursos antes da eleição
# df, name = preprocessing ( *discourses_extract ( *list_extract("02/07/2022", "29/10/2022") ) )

.....................................
... Função list_extract iniciada! ...
... URL base:  https://www.camara.leg.br/internet/sitaqweb/resultadoPesquisaDiscursos.asp?txIndexacao=&CurrentPage=1&BasePesq=plenario&txOrador=&txPartido=&dtInicio=02/07/2022&dtFim=29/10/2022&txUF=&txSessao=&listaTipoSessao=&listaTipoInterv=&inFalaPres=&listaTipoFala=&listaFaseSessao=&txAparteante=&listaEtapa=&CampoOrdenacao=dtSessao&TipoOrdenacao=DESC&PageSize=550&txTexto=&txSumario= ...
... Acessando página! ...
... Status: 200 ...
... Sucesso!!! ...
... O número total de discursos encontrados é: 2329 ...
... O número total de páginas é: 5 ...
... Acessando páginas adicionais! ...
... Adicionando os discursos da página: ... 2
... Adicionando os discursos da página: ... 3
... Adicionando os discursos da página: ... 4
... Adicionando os discursos da página: ... 5
... Formatando dados extraídos! ...
... Salvando as informações! ...
... Função list_extract encerrada! ...
......................................
...........................................
... Função discourses_extract iniciada! ...
... Extaíndo discurso da 1ª URL: https://www.camara.leg.br/internet/sitaqweb/TextoHTML.asp?etapa=5&nuSessao=141.2022&nuQuarto=2659804&nuOrador=1&nuInsercao=1&dtHorarioQuarto=13%3A48&sgFaseSessao=OD&Data=19%2F10%2F2022&txApelido=Erika+Kokay&txFaseSessao=Ordem+do+Dia&txTipoSessao=Ordin%C3%A1ria+-+CD&dtHoraQuarto=13%3A48 ...
... Extaíndo discurso da 2ª URL: https://www.camara.leg.br/internet/sitaqweb/TextoHTML.asp?etapa=5&nuSessao=141.2022&nuQuarto=2659799&nuOrador=1&nuInsercao=1&dtHorarioQuarto=13%3A40&sgFaseSessao=OD&Data=19%2F10%2F2022&txApelido=Hildo+Rocha&txFaseSessao=Ordem+do+Dia&txTipoSessao=Ordin%C3%A1ria+-+CD&dtHoraQuarto=13%3A40 ...
... Extaíndo discurso da 3ª URL: https://www.camara.leg.br/internet/sitaqweb/TextoHTML.asp?etapa=5&nuSessao=141.2022&nuQuarto=2659796&nuOrador=1&nuInsercao=1&dtHorarioQuarto=13%3A36&sgFaseSessao=OD&Data=19%2F10%2F2022&txApelido=Pompeo+de+Mattos&txFaseSessao=Ordem+do+Dia&txTipoSessao=Ordin%C3%A1ria+-+CD&dtHoraQuarto=13%3A36 ...
... Extaíndo discurso da 4ª URL: https://www.camara.leg.br/internet/sitaqweb/TextoHTML.asp?etapa=5&nuSessao=141.2022&nuQuarto=2659794&nuOrador=1&nuInsercao=1&dtHorarioQuarto=13%3A36&sgFaseSessao=OD&Data=19%2F10%2F2022&txApelido=Erika+Kokay&txFaseSessao=Ordem+do+Dia&txTipoSessao=Ordin%C3%A1ria+-+CD&dtHoraQuarto=13%3A36 ...
... Extaíndo discurso da 5ª URL: https://www.camara.leg.br/internet/sitaqweb/TextoHTML.asp?etapa=5&nuSessao=141.2022&nuQuarto=2659786&nuOrador=1&nuInsercao=1&dtHorarioQuarto=13%3A32&sgFaseSessao=OD&Data=19%2F10%2F2022&txApelido=Pompeo+de+Mattos&txFaseSessao=Ordem+do+Dia&txTipoSessao=Ordin%C3%A1ria+-+CD&dtHoraQuarto=13%3A32 ...
... Extaíndo discurso da 6ª URL: https://www.camara.leg.br/internet/sitaqweb/TextoHTML.asp?etapa=5&nuSessao=141.2022&nuQuarto=2659790&nuOrador=1&nuInsercao=1&dtHorarioQuarto=13%3A32&sgFaseSessao=OD&Data=19%2F10%2F2022&txApelido=Kim+Kataguiri&txFaseSessao=Ordem+do+Dia&txTipoSessao=Ordin%C3%A1ria+-+CD&dtHoraQuarto=13%3A32 ...
... Extaíndo discurso da 7ª URL: https://www.camara.leg.br/internet/sitaqweb/TextoHTML.asp?etapa=5&nuSessao=141.2022&nuQuarto=2659781&nuOrador=1&nuInsercao=1&dtHorarioQuarto=13%3A28&sgFaseSessao=OD&Data=19%2F10%2F2022&txApelido=Hildo+Rocha&txFaseSessao=Ordem+do+Dia&txTipoSessao=Ordin%C3%A1ria+-+CD&dtHoraQuarto=13%3A28 ...
... Extaíndo discurso da 8ª URL: https://www.camara.leg.br/internet/sitaqweb/TextoHTML.asp?etapa=5&nuSessao=141.2022&nuQuarto=2659773&nuOrador=1&nuInsercao=1&dtHorarioQuarto=13%3A24&sgFaseSessao=OD&Data=19%2F10%2F2022&txApelido=Erika+Kokay&txFaseSessao=Ordem+do+Dia&txTipoSessao=Ordin%C3%A1ria+-+CD&dtHoraQuarto=13%3A24 ...
... Extaíndo discurso da 9ª URL: https://www.camara.leg.br/internet/sitaqweb/TextoHTML.asp?etapa=5&nuSessao=141.2022&nuQuarto=2659762&nuOrador=1&nuInsercao=1&dtHorarioQuarto=13%3A12&sgFaseSessao=OD&Data=19%2F10%2F2022&txApelido=Vivi+Reis&txFaseSessao=Ordem+do+Dia&txTipoSessao=Ordin%C3%A1ria+-+CD&dtHoraQuarto=13%3A12 ...
... Extaíndo discurso da 10ª URL: https://www.camara.leg.br/internet/sitaqweb/TextoHTML.asp?etapa=5&nuSessao=141.2022&nuQuarto=2659757&nuOrador=1&nuInsercao=1&dtHorarioQuarto=13%3A08&sgFaseSessao=OD&Data=19%2F10%2F2022&txApelido=Aliel+Machado&txFaseSessao=Ordem+do+Dia&txTipoSessao=Ordin%C3%A1ria+-+CD&dtHoraQuarto=13%3A08 ...
... Extaíndo discurso da 11ª URL: https://www.camara.leg.br/internet/sitaqweb/TextoHTML.asp?etapa=5&nuSessao=141.2022&nuQuarto=2660656&nuOrador=1&nuInsercao=1&dtHorarioQuarto=12%3A56&sgFaseSessao=OD&Data=19%2F10%2F2022&txApelido=Kim+Kataguiri&txFaseSessao=Ordem+do+Dia&txTipoSessao=Ordin%C3%A1ria+-+CD&dtHoraQuarto=12%3A56 ...
... Extaíndo discurso da 12ª URL: https://www.camara.leg.br/internet/sitaqweb/TextoHTML.asp?etapa=5&nuSessao=141.2022&nuQuarto=2660654&nuOrador=1&nuInsercao=1&dtHorarioQuarto=12%3A56&sgFaseSessao=OD&Data=19%2F10%2F2022&txApelido=Hildo+Rocha&txFaseSessao=Ordem+do+Dia&txTipoSessao=Ordin%C3%A1ria+-+CD&dtHoraQuarto=12%3A56 ...
... Extaíndo discurso da 13ª URL: https://www.camara.leg.br/internet/sitaqweb/TextoHTML.asp?etapa=5&nuSessao=141.2022&nuQuarto=2659745&nuOrador=1&nuInsercao=1&dtHorarioQuarto=12%3A52&sgFaseSessao=OD&Data=19%2F10%2F2022&txApelido=Vivi+Reis&txFaseSessao=Ordem+do+Dia&txTipoSessao=Ordin%C3%A1ria+-+CD&dtHoraQuarto=12%3A52 ...
... Extaíndo discurso da 14ª URL: https://www.camara.leg.br/internet/sitaqweb/TextoHTML.asp?etapa=5&nuSessao=141.2022&nuQuarto=2659756&nuOrador=1&nuInsercao=1&dtHorarioQuarto=12%3A52&sgFaseSessao=OD&Data=19%2F10%2F2022&txApelido=Erika+Kokay&txFaseSessao=Ordem+do+Dia&txTipoSessao=Ordin%C3%A1ria+-+CD&dtHoraQuarto=12%3A52 ...
... Extaíndo discurso da 15ª URL: https://www.camara.leg.br/internet/sitaqweb/TextoHTML.asp?etapa=5&nuSessao=141.2022&nuQuarto=2659747&nuOrador=1&nuInsercao=1&dtHorarioQuarto=12%3A52&sgFaseSessao=OD&Data=19%2F10%2F2022&txApelido=Erika+Kokay&txFaseSessao=Ordem+do+Dia&txTipoSessao=Ordin%C3%A1ria+-+CD&dtHoraQuarto=12%3A52 ...
... Extaíndo discurso da 16ª URL: https://www.camara.leg.br/internet/sitaqweb/TextoHTML.asp?etapa=5&nuSessao=141.2022&nuQuarto=2659742&nuOrador=1&nuInsercao=1&dtHorarioQuarto=12%3A48&sgFaseSessao=OD&Data=19%2F10%2F2022&txApelido=Erika+Kokay&txFaseSessao=Ordem+do+Dia&txTipoSessao=Ordin%C3%A1ria+-+CD&dtHoraQuarto=12%3A48 ...
... Extaíndo discurso da 17ª URL: https://www.camara.leg.br/internet/sitaqweb/TextoHTML.asp?etapa=5&nuSessao=141.2022&nuQuarto=2659693&nuOrador=1&nuInsercao=1&dtHorarioQuarto=12%3A44&sgFaseSessao=OD&Data=19%2F10%2F2022&txApelido=Vivi+Reis&txFaseSessao=Ordem+do+Dia&txTipoSessao=Ordin%C3%A1ria+-+CD&dtHoraQuarto=12%3A44 ...
... Extaíndo discurso da 18ª URL: https://www.camara.leg.br/internet/sitaqweb/TextoHTML.asp?etapa=5&nuSessao=141.2022&nuQuarto=2659708&nuOrador=1&nuInsercao=1&dtHorarioQuarto=12%3A44&sgFaseSessao=OD&Data=19%2F10%2F2022&txApelido=Erika+Kokay&txFaseSessao=Ordem+do+Dia&txTipoSessao=Ordin%C3%A1ria+-+CD&dtHoraQuarto=12%3A44 ...
... Extaíndo discurso da 19ª URL: https://www.camara.leg.br/internet/sitaqweb/TextoHTML.asp?etapa=5&nuSessao=141.2022&nuQuarto=2660022&nuOrador=1&nuInsercao=1&dtHorarioQuarto=12%3A40&sgFaseSessao=OD&Data=19%2F10%2F2022&txApelido=Pompeo+de+Mattos&txFaseSessao=Ordem+do+Dia&txTipoSessao=Ordin%C3%A1ria+-+CD&dtHoraQuarto=12%3A40 ...
... Extaíndo discurso da 20ª URL: https://www.camara.leg.br/internet/sitaqweb/TextoHTML.asp?etapa=5&nuSessao=141.2022&nuQuarto=2660019&nuOrador=1&nuInsercao=1&dtHorarioQuarto=12%3A40&sgFaseSessao=OD&Data=19%2F10%2F2022&txApelido=Erika+Kokay&txFaseSessao=Ordem+do+Dia&txTipoSessao=Ordin%C3%A1ria+-+CD&dtHoraQuarto=12%3A40 ...
... Extaíndo discurso da 21ª URL: https://www.camara.leg.br/internet/sitaqweb/TextoHTML.asp?etapa=5&nuSessao=141.2022&nuQuarto=2659989&nuOrador=1&nuInsercao=1&dtHorarioQuarto=12%3A36&sgFaseSessao=OD&Data=19%2F10%2F2022&txApelido=Erika+Kokay&txFaseSessao=Ordem+do+Dia&txTipoSessao=Ordin%C3%A1ria+-+CD&dtHoraQuarto=12%3A36 ...
... Extaíndo discurso da 22ª URL: https://www.camara.leg.br/internet/sitaqweb/TextoHTML.asp?etapa=5&nuSessao=141.2022&nuQuarto=2659979&nuOrador=1&nuInsercao=1&dtHorarioQuarto=12%3A36&sgFaseSessao=OD&Data=19%2F10%2F2022&txApelido=Alexis+Fonteyne&txFaseSessao=Ordem+do+Dia&txTipoSessao=Ordin%C3%A1ria+-+CD&dtHoraQuarto=12%3A36 ...
... Extaíndo discurso da 23ª URL: https://www.camara.leg.br/internet/sitaqweb/TextoHTML.asp?etapa=5&nuSessao=141.2022&nuQuarto=2659973&nuOrador=1&nuInsercao=1&dtHorarioQuarto=12%3A32&sgFaseSessao=OD&Data=19%2F10%2F2022&txApelido=Pompeo+de+Mattos&txFaseSessao=Ordem+do+Dia&txTipoSessao=Ordin%C3%A1ria+-+CD&dtHoraQuarto=12%3A32 ...
... Extaíndo discurso da 24ª URL: https://www.camara.leg.br/internet/sitaqweb/TextoHTML.asp?etapa=5&nuSessao=141.2022&nuQuarto=2659964&nuOrador=1&nuInsercao=1&dtHorarioQuarto=12%3A32&sgFaseSessao=OD&Data=19%2F10%2F2022&txApelido=Hildo+Rocha&txFaseSessao=Ordem+do+Dia&txTipoSessao=Ordin%C3%A1ria+-+CD&dtHoraQuarto=12%3A32 ...
... Extaíndo discurso da 25ª URL: https://www.camara.leg.br/internet/sitaqweb/TextoHTML.asp?etapa=5&nuSessao=141.2022&nuQuarto=2659928&nuOrador=1&nuInsercao=1&dtHorarioQuarto=12%3A28&sgFaseSessao=OD&Data=19%2F10%2F2022&txApelido=Pompeo+de+Mattos&txFaseSessao=Ordem+do+Dia&txTipoSessao=Ordin%C3%A1ria+-+CD&dtHoraQuarto=12%3A28 ...
... Extaíndo discurso da 26ª URL: https://www.camara.leg.br/internet/sitaqweb/TextoHTML.asp?etapa=5&nuSessao=141.2022&nuQuarto=2659934&nuOrador=1&nuInsercao=1&dtHorarioQuarto=12%3A28&sgFaseSessao=OD&Data=19%2F10%2F2022&txApelido=Erika+Kokay&txFaseSessao=Ordem+do+Dia&txTipoSessao=Ordin%C3%A1ria+-+CD&dtHoraQuarto=12%3A28 ...
... Extaíndo discurso da 27ª URL: https://www.camara.leg.br/internet/sitaqweb/TextoHTML.asp?etapa=5&nuSessao=141.2022&nuQuarto=2659929&nuOrador=1&nuInsercao=1&dtHorarioQuarto=12%3A28&sgFaseSessao=OD&Data=19%2F10%2F2022&txApelido=Erika+Kokay&txFaseSessao=Ordem+do+Dia&txTipoSessao=Ordin%C3%A1ria+-+CD&dtHoraQuarto=12%3A28 ...
... Extaíndo discurso da 28ª URL: https://www.camara.leg.br/internet/sitaqweb/TextoHTML.asp?etapa=5&nuSessao=141.2022&nuQuarto=2659924&nuOrador=1&nuInsercao=1&dtHorarioQuarto=12%3A24&sgFaseSessao=OD&Data=19%2F10%2F2022&txApelido=Vivi+Reis&txFaseSessao=Ordem+do+Dia&txTipoSessao=Ordin%C3%A1ria+-+CD&dtHoraQuarto=12%3A24 ...
... Extaíndo discurso da 29ª URL: https://www.camara.leg.br/internet/sitaqweb/TextoHTML.asp?etapa=5&nuSessao=141.2022&nuQuarto=2659926&nuOrador=1&nuInsercao=1&dtHorarioQuarto=12%3A24&sgFaseSessao=OD&Data=19%2F10%2F2022&txApelido=Tiago+Mitraud&txFaseSessao=Ordem+do+Dia&txTipoSessao=Ordin%C3%A1ria+-+CD&dtHoraQuarto=12%3A24 ...
... Extaíndo discurso da 30ª URL: https://www.camara.leg.br/internet/sitaqweb/TextoHTML.asp?etapa=5&nuSessao=141.2022&nuQuarto=2659914&nuOrador=1&nuInsercao=1&dtHorarioQuarto=12%3A24&sgFaseSessao=OD&Data=19%2F10%2F2022&txApelido=Erika+Kokay&txFaseSessao=Ordem+do+Dia&txTipoSessao=Ordin%C3%A1ria+-+CD&dtHoraQuarto=12%3A24 ...
... Extaíndo discurso da 31ª URL: https://www.camara.leg.br/internet/sitaqweb/TextoHTML.asp?etapa=5&nuSessao=141.2022&nuQuarto=2659909&nuOrador=1&nuInsercao=1&dtHorarioQuarto=12%3A20&sgFaseSessao=OD&Data=19%2F10%2F2022&txApelido=Erika+Kokay&txFaseSessao=Ordem+do+Dia&txTipoSessao=Ordin%C3%A1ria+-+CD&dtHoraQuarto=12%3A20 ...
... Extaíndo discurso da 32ª URL: https://www.camara.leg.br/internet/sitaqweb/TextoHTML.asp?etapa=5&nuSessao=141.2022&nuQuarto=2659907&nuOrador=1&nuInsercao=1&dtHorarioQuarto=12%3A20&sgFaseSessao=OD&Data=19%2F10%2F2022&txApelido=Erika+Kokay&txFaseSessao=Ordem+do+Dia&txTipoSessao=Ordin%C3%A1ria+-+CD&dtHoraQuarto=12%3A20 ...
... Extaíndo discurso da 33ª URL: https://www.camara.leg.br/internet/sitaqweb/TextoHTML.asp?etapa=5&nuSessao=141.2022&nuQuarto=2659899&nuOrador=1&nuInsercao=1&dtHorarioQuarto=12%3A16&sgFaseSessao=OD&Data=19%2F10%2F2022&txApelido=Erika+Kokay&txFaseSessao=Ordem+do+Dia&txTipoSessao=Ordin%C3%A1ria+-+CD&dtHoraQuarto=12%3A16 ...
... Extaíndo discurso da 34ª URL: https://www.camara.leg.br/internet/sitaqweb/TextoHTML.asp?etapa=5&nuSessao=141.2022&nuQuarto=2659687&nuOrador=1&nuInsercao=1&dtHorarioQuarto=12%3A04&sgFaseSessao=OD&Data=19%2F10%2F2022&txApelido=Erika+Kokay&txFaseSessao=Ordem+do+Dia&txTipoSessao=Ordin%C3%A1ria+-+CD&dtHoraQuarto=12%3A04 ...
... Extaíndo discurso da 35ª URL: https://www.camara.leg.br/internet/sitaqweb/TextoHTML.asp?etapa=5&nuSessao=141.2022&nuQuarto=2659667&nuOrador=1&nuInsercao=1&dtHorarioQuarto=12%3A00&sgFaseSessao=OD&Data=19%2F10%2F2022&txApelido=Erika+Kokay&txFaseSessao=Ordem+do+Dia&txTipoSessao=Ordin%C3%A1ria+-+CD&dtHoraQuarto=12%3A00 ...
... Extaíndo discurso da 36ª URL: https://www.camara.leg.br/internet/sitaqweb/TextoHTML.asp?etapa=5&nuSessao=141.2022&nuQuarto=2659673&nuOrador=1&nuInsercao=1&dtHorarioQuarto=12%3A00&sgFaseSessao=OD&Data=19%2F10%2F2022&txApelido=Erika+Kokay&txFaseSessao=Ordem+do+Dia&txTipoSessao=Ordin%C3%A1ria+-+CD&dtHoraQuarto=12%3A00 ...
... Extaíndo discurso da 37ª URL: https://www.camara.leg.br/internet/sitaqweb/TextoHTML.asp?etapa=5&nuSessao=141.2022&nuQuarto=2659671&nuOrador=1&nuInsercao=1&dtHorarioQuarto=12%3A00&sgFaseSessao=OD&Data=19%2F10%2F2022&txApelido=Daniel+Almeida&txFaseSessao=Ordem+do+Dia&txTipoSessao=Ordin%C3%A1ria+-+CD&dtHoraQuarto=12%3A00 ...
... Extaíndo discurso da 38ª URL: https://www.camara.leg.br/internet/sitaqweb/TextoHTML.asp?etapa=5&nuSessao=141.2022&nuQuarto=2659669&nuOrador=1&nuInsercao=1&dtHorarioQuarto=12%3A00&sgFaseSessao=OD&Data=19%2F10%2F2022&txApelido=Alex+Manente&txFaseSessao=Ordem+do+Dia&txTipoSessao=Ordin%C3%A1ria+-+CD&dtHoraQuarto=12%3A00 ...
... Extaíndo discurso da 39ª URL: https://www.camara.leg.br/internet/sitaqweb/TextoHTML.asp?etapa=5&nuSessao=141.2022&nuQuarto=2659664&nuOrador=1&nuInsercao=1&dtHorarioQuarto=11%3A56&sgFaseSessao=OD&Data=19%2F10%2F2022&txApelido=Vivi+Reis&txFaseSessao=Ordem+do+Dia&txTipoSessao=Ordin%C3%A1ria+-+CD&dtHoraQuarto=11%3A56 ...
... Extaíndo discurso da 40ª URL: https://www.camara.leg.br/internet/sitaqweb/TextoHTML.asp?etapa=5&nuSessao=141.2022&nuQuarto=2659662&nuOrador=1&nuInsercao=1&dtHorarioQuarto=11%3A56&sgFaseSessao=OD&Data=19%2F10%2F2022&txApelido=Tiago+Mitraud&txFaseSessao=Ordem+do+Dia&txTipoSessao=Ordin%C3%A1ria+-+CD&dtHoraQuarto=11%3A56 ...
... Extaíndo discurso da 41ª URL: https://www.camara.leg.br/internet/sitaqweb/TextoHTML.asp?etapa=5&nuSessao=141.2022&nuQuarto=2659630&nuOrador=1&nuInsercao=1&dtHorarioQuarto=11%3A52&sgFaseSessao=OD&Data=19%2F10%2F2022&txApelido=Professor+Alcides&txFaseSessao=Ordem+do+Dia&txTipoSessao=Ordin%C3%A1ria+-+CD&dtHoraQuarto=11%3A52 ...
... Extaíndo discurso da 42ª URL: https://www.camara.leg.br/internet/sitaqweb/TextoHTML.asp?etapa=5&nuSessao=141.2022&nuQuarto=2659622&nuOrador=1&nuInsercao=1&dtHorarioQuarto=11%3A52&sgFaseSessao=OD&Data=19%2F10%2F2022&txApelido=Erika+Kokay&txFaseSessao=Ordem+do+Dia&txTipoSessao=Ordin%C3%A1ria+-+CD&dtHoraQuarto=11%3A52 ...
... Extaíndo discurso da 43ª URL: https://www.camara.leg.br/internet/sitaqweb/TextoHTML.asp?etapa=5&nuSessao=141.2022&nuQuarto=2659633&nuOrador=1&nuInsercao=1&dtHorarioQuarto=11%3A52&sgFaseSessao=OD&Data=19%2F10%2F2022&txApelido=Erika+Kokay&txFaseSessao=Ordem+do+Dia&txTipoSessao=Ordin%C3%A1ria+-+CD&dtHoraQuarto=11%3A52 ...
... Extaíndo discurso da 44ª URL: https://www.camara.leg.br/internet/sitaqweb/TextoHTML.asp?etapa=5&nuSessao=141.2022&nuQuarto=2659619&nuOrador=1&nuInsercao=1&dtHorarioQuarto=11%3A52&sgFaseSessao=OD&Data=19%2F10%2F2022&txApelido=Carlos+Henrique+Gaguim&txFaseSessao=Ordem+do+Dia&txTipoSessao=Ordin%C3%A1ria+-+CD&dtHoraQuarto=11%3A52 ...
... Extaíndo discurso da 45ª URL: https://www.camara.leg.br/internet/sitaqweb/TextoHTML.asp?etapa=5&nuSessao=141.2022&nuQuarto=2659615&nuOrador=1&nuInsercao=1&dtHorarioQuarto=11%3A48&sgFaseSessao=OD&Data=19%2F10%2F2022&txApelido=Luizianne+Lins&txFaseSessao=Ordem+do+Dia&txTipoSessao=Ordin%C3%A1ria+-+CD&dtHoraQuarto=11%3A48 ...
... Extaíndo discurso da 46ª URL: https://www.camara.leg.br/internet/sitaqweb/TextoHTML.asp?etapa=5&nuSessao=141.2022&nuQuarto=2659610&nuOrador=1&nuInsercao=1&dtHorarioQuarto=11%3A44&sgFaseSessao=OD&Data=19%2F10%2F2022&txApelido=Aliel+Machado&txFaseSessao=Ordem+do+Dia&txTipoSessao=Ordin%C3%A1ria+-+CD&dtHoraQuarto=11%3A44 ...
... Extaíndo discurso da 47ª URL: https://www.camara.leg.br/internet/sitaqweb/TextoHTML.asp?etapa=5&nuSessao=141.2022&nuQuarto=2659604&nuOrador=1&nuInsercao=1&dtHorarioQuarto=11%3A40&sgFaseSessao=BC&Data=19%2F10%2F2022&txApelido=Professor+Alcides&txFaseSessao=Breves+Comunica%C3%A7%C3%B5es&txTipoSessao=Ordin%C3%A1ria+-+CD&dtHoraQuarto=11%3A40 ...
... Extaíndo discurso da 48ª URL: https://www.camara.leg.br/internet/sitaqweb/TextoHTML.asp?etapa=5&nuSessao=141.2022&nuQuarto=2659606&nuOrador=1&nuInsercao=1&dtHorarioQuarto=11%3A40&sgFaseSessao=BC&Data=19%2F10%2F2022&txApelido=Luizianne+Lins&txFaseSessao=Breves+Comunica%C3%A7%C3%B5es&txTipoSessao=Ordin%C3%A1ria+-+CD&dtHoraQuarto=11%3A40 ...
... Extaíndo discurso da 49ª URL: https://www.camara.leg.br/internet/sitaqweb/TextoHTML.asp?etapa=5&nuSessao=141.2022&nuQuarto=2659600&nuOrador=1&nuInsercao=1&dtHorarioQuarto=11%3A36&sgFaseSessao=BC&Data=19%2F10%2F2022&txApelido=Marcel+Van+Hattem&txFaseSessao=Breves+Comunica%C3%A7%C3%B5es&txTipoSessao=Ordin%C3%A1ria+-+CD&dtHoraQuarto=11%3A36 ...
... Extaíndo discurso da 50ª URL: https://www.camara.leg.br/internet/sitaqweb/TextoHTML.asp?etapa=5&nuSessao=141.2022&nuQuarto=2659595&nuOrador=1&nuInsercao=1&dtHorarioQuarto=11%3A28&sgFaseSessao=BC&Data=19%2F10%2F2022&txApelido=Luizianne+Lins&txFaseSessao=Breves+Comunica%C3%A7%C3%B5es&txTipoSessao=Ordin%C3%A1ria+-+CD&dtHoraQuarto=11%3A28 ...
... Extaíndo discurso da 51ª URL: https://www.camara.leg.br/internet/sitaqweb/TextoHTML.asp?etapa=5&nuSessao=141.2022&nuQuarto=2659587&nuOrador=1&nuInsercao=1&dtHorarioQuarto=11%3A20&sgFaseSessao=BC&Data=19%2F10%2F2022&txApelido=Eliza+Virg%C3%ADnia&txFaseSessao=Breves+Comunica%C3%A7%C3%B5es&txTipoSessao=Ordin%C3%A1ria+-+CD&dtHoraQuarto=11%3A20 ...
... Extaíndo discurso da 52ª URL: https://www.camara.leg.br/internet/sitaqweb/TextoHTML.asp?etapa=5&nuSessao=141.2022&nuQuarto=2659581&nuOrador=1&nuInsercao=1&dtHorarioQuarto=11%3A12&sgFaseSessao=BC&Data=19%2F10%2F2022&txApelido=Aluisio+Mendes&txFaseSessao=Breves+Comunica%C3%A7%C3%B5es&txTipoSessao=Ordin%C3%A1ria+-+CD&dtHoraQuarto=11%3A12 ...
... Extaíndo discurso da 53ª URL: https://www.camara.leg.br/internet/sitaqweb/TextoHTML.asp?etapa=5&nuSessao=141.2022&nuQuarto=2659583&nuOrador=1&nuInsercao=1&dtHorarioQuarto=11%3A12&sgFaseSessao=BC&Data=19%2F10%2F2022&txApelido=A%C3%A9cio+Neves&txFaseSessao=Breves+Comunica%C3%A7%C3%B5es&txTipoSessao=Ordin%C3%A1ria+-+CD&dtHoraQuarto=11%3A12 ...
... Extaíndo discurso da 54ª URL: https://www.camara.leg.br/internet/sitaqweb/TextoHTML.asp?etapa=5&nuSessao=141.2022&nuQuarto=2659574&nuOrador=1&nuInsercao=1&dtHorarioQuarto=11%3A04&sgFaseSessao=BC&Data=19%2F10%2F2022&txApelido=Aureo+Ribeiro&txFaseSessao=Breves+Comunica%C3%A7%C3%B5es&txTipoSessao=Ordin%C3%A1ria+-+CD&dtHoraQuarto=11%3A04 ...
... Extaíndo discurso da 55ª URL: https://www.camara.leg.br/internet/sitaqweb/TextoHTML.asp?etapa=5&nuSessao=141.2022&nuQuarto=2659570&nuOrador=1&nuInsercao=1&dtHorarioQuarto=11%3A00&sgFaseSessao=BC&Data=19%2F10%2F2022&txApelido=Luizianne+Lins&txFaseSessao=Breves+Comunica%C3%A7%C3%B5es&txTipoSessao=Ordin%C3%A1ria+-+CD&dtHoraQuarto=11%3A00 ...
... Extaíndo discurso da 56ª URL: https://www.camara.leg.br/internet/sitaqweb/TextoHTML.asp?etapa=5&nuSessao=141.2022&nuQuarto=2659569&nuOrador=1&nuInsercao=1&dtHorarioQuarto=11%3A00&sgFaseSessao=BC&Data=19%2F10%2F2022&txApelido=Domingos+Neto&txFaseSessao=Breves+Comunica%C3%A7%C3%B5es&txTipoSessao=Ordin%C3%A1ria+-+CD&dtHoraQuarto=11%3A00 ...
... Extaíndo discurso da 57ª URL: https://www.camara.leg.br/internet/sitaqweb/TextoHTML.asp?etapa=5&nuSessao=141.2022&nuQuarto=2659566&nuOrador=1&nuInsercao=1&dtHorarioQuarto=10%3A56&sgFaseSessao=BC&Data=19%2F10%2F2022&txApelido=Pompeo+de+Mattos&txFaseSessao=Breves+Comunica%C3%A7%C3%B5es&txTipoSessao=Ordin%C3%A1ria+-+CD&dtHoraQuarto=10%3A56 ...

In [ ]:
# discursos depois da eleição
# df, name = preprocessing ( *discourses_extract ( *list_extract("31/10/2022", "02/01/2023") ) )

.....................................
... Função list_extract iniciada! ...
... URL base:  https://www.camara.leg.br/internet/sitaqweb/resultadoPesquisaDiscursos.asp?txIndexacao=&CurrentPage=1&BasePesq=plenario&txOrador=&txPartido=&dtInicio=31/10/2022&dtFim=02/01/2023&txUF=&txSessao=&listaTipoSessao=&listaTipoInterv=&inFalaPres=&listaTipoFala=&listaFaseSessao=&txAparteante=&listaEtapa=&CampoOrdenacao=dtSessao&TipoOrdenacao=DESC&PageSize=550&txTexto=&txSumario= ...
... Acessando página! ...
... Status: 200 ...
... Sucesso!!! ...
... O número total de discursos encontrados é: 2401 ...
... O número total de páginas é: 5 ...
... Acessando páginas adicionais! ...
... Adicionando os discursos da página: ... 2
... Adicionando os discursos da página: ... 3
... Adicionando os discursos da página: ... 4
... Adicionando os discursos da página: ... 5
... Formatando dados extraídos! ...
... Salvando as informações! ...
... Função list_extract encerrada! ...
......................................
...........................................
... Função discourses_extract iniciada! ...
... Extaíndo discurso da 1ª URL: https://www.camara.leg.br/internet/sitaqweb/TextoHTML.asp?etapa=5&nuSessao=183.2022&nuQuarto=2761774&nuOrador=1&nuInsercao=1&dtHorarioQuarto=23%3A52&sgFaseSessao=OD&Data=22%2F12%2F2022&txApelido=Marcel+Van+Hattem&txFaseSessao=Ordem+do+Dia&txTipoSessao=Ordin%C3%A1ria+-+CD&dtHoraQuarto=23%3A52 ...
... Extaíndo discurso da 2ª URL: https://www.camara.leg.br/internet/sitaqweb/TextoHTML.asp?etapa=5&nuSessao=183.2022&nuQuarto=2761759&nuOrador=1&nuInsercao=1&dtHorarioQuarto=23%3A48&sgFaseSessao=OD&Data=22%2F12%2F2022&txApelido=Renildo+Calheiros&txFaseSessao=Ordem+do+Dia&txTipoSessao=Ordin%C3%A1ria+-+CD&dtHoraQuarto=23%3A48 ...
... Extaíndo discurso da 3ª URL: https://www.camara.leg.br/internet/sitaqweb/TextoHTML.asp?etapa=5&nuSessao=183.2022&nuQuarto=2761761&nuOrador=1&nuInsercao=1&dtHorarioQuarto=23%3A48&sgFaseSessao=OD&Data=22%2F12%2F2022&txApelido=Reginaldo+Lopes&txFaseSessao=Ordem+do+Dia&txTipoSessao=Ordin%C3%A1ria+-+CD&dtHoraQuarto=23%3A48 ...
... Extaíndo discurso da 4ª URL: https://www.camara.leg.br/internet/sitaqweb/TextoHTML.asp?etapa=5&nuSessao=183.2022&nuQuarto=2761771&nuOrador=1&nuInsercao=1&dtHorarioQuarto=23%3A48&sgFaseSessao=OD&Data=22%2F12%2F2022&txApelido=Marcel+Van+Hattem&txFaseSessao=Ordem+do+Dia&txTipoSessao=Ordin%C3%A1ria+-+CD&dtHoraQuarto=23%3A48 ...
... Extaíndo discurso da 5ª URL: https://www.camara.leg.br/internet/sitaqweb/TextoHTML.asp?etapa=5&nuSessao=183.2022&nuQuarto=2761744&nuOrador=1&nuInsercao=1&dtHorarioQuarto=23%3A28&sgFaseSessao=OD&Data=22%2F12%2F2022&txApelido=Bia+Kicis&txFaseSessao=Ordem+do+Dia&txTipoSessao=Ordin%C3%A1ria+-+CD&dtHoraQuarto=23%3A28 ...
... Extaíndo discurso da 6ª URL: https://www.camara.leg.br/internet/sitaqweb/TextoHTML.asp?etapa=5&nuSessao=183.2022&nuQuarto=2761730&nuOrador=1&nuInsercao=1&dtHorarioQuarto=22%3A48&sgFaseSessao=OD&Data=22%2F12%2F2022&txApelido=Tiago+Mitraud&txFaseSessao=Ordem+do+Dia&txTipoSessao=Ordin%C3%A1ria+-+CD&dtHoraQuarto=22%3A48 ...
... Extaíndo discurso da 7ª URL: https://www.camara.leg.br/internet/sitaqweb/TextoHTML.asp?etapa=5&nuSessao=183.2022&nuQuarto=2761727&nuOrador=1&nuInsercao=1&dtHorarioQuarto=22%3A40&sgFaseSessao=OD&Data=22%2F12%2F2022&txApelido=Reginaldo+Lopes&txFaseSessao=Ordem+do+Dia&txTipoSessao=Ordin%C3%A1ria+-+CD&dtHoraQuarto=22%3A40 ...
... Extaíndo discurso da 8ª URL: https://www.camara.leg.br/internet/sitaqweb/TextoHTML.asp?etapa=5&nuSessao=183.2022&nuQuarto=2761817&nuOrador=1&nuInsercao=1&dtHorarioQuarto=22%3A28&sgFaseSessao=OD&Data=22%2F12%2F2022&txApelido=Paula+Belmonte&txFaseSessao=Ordem+do+Dia&txTipoSessao=Ordin%C3%A1ria+-+CD&dtHoraQuarto=22%3A28 ...
... Extaíndo discurso da 9ª URL: https://www.camara.leg.br/internet/sitaqweb/TextoHTML.asp?etapa=5&nuSessao=183.2022&nuQuarto=2761720&nuOrador=1&nuInsercao=1&dtHorarioQuarto=22%3A08&sgFaseSessao=OD&Data=22%2F12%2F2022&txApelido=Renildo+Calheiros&txFaseSessao=Ordem+do+Dia&txTipoSessao=Ordin%C3%A1ria+-+CD&dtHoraQuarto=22%3A08 ...
... Extaíndo discurso da 10ª URL: https://www.camara.leg.br/internet/sitaqweb/TextoHTML.asp?etapa=5&nuSessao=183.2022&nuQuarto=2761713&nuOrador=1&nuInsercao=1&dtHorarioQuarto=22%3A00&sgFaseSessao=BC&Data=22%2F12%2F2022&txApelido=S%C3%A2mia+Bomfim&txFaseSessao=Breves+Comunica%C3%A7%C3%B5es&txTipoSessao=Ordin%C3%A1ria+-+CD&dtHoraQuarto=22%3A00 ...
... Extaíndo discurso da 11ª URL: https://www.camara.leg.br/internet/sitaqweb/TextoHTML.asp?etapa=5&nuSessao=183.2022&nuQuarto=2761710&nuOrador=1&nuInsercao=1&dtHorarioQuarto=21%3A56&sgFaseSessao=BC&Data=22%2F12%2F2022&txApelido=Bia+Kicis&txFaseSessao=Breves+Comunica%C3%A7%C3%B5es&txTipoSessao=Ordin%C3%A1ria+-+CD&dtHoraQuarto=21%3A56 ...
... Extaíndo discurso da 12ª URL: https://www.camara.leg.br/internet/sitaqweb/TextoHTML.asp?etapa=5&nuSessao=183.2022&nuQuarto=2761704&nuOrador=1&nuInsercao=1&dtHorarioQuarto=21%3A48&sgFaseSessao=BC&Data=22%2F12%2F2022&txApelido=Marcel+Van+Hattem&txFaseSessao=Breves+Comunica%C3%A7%C3%B5es&txTipoSessao=Ordin%C3%A1ria+-+CD&dtHoraQuarto=21%3A48 ...
... Extaíndo discurso da 13ª URL: https://www.camara.leg.br/internet/sitaqweb/TextoHTML.asp?etapa=5&nuSessao=183.2022&nuQuarto=2761698&nuOrador=1&nuInsercao=1&dtHorarioQuarto=21%3A44&sgFaseSessao=BC&Data=22%2F12%2F2022&txApelido=Renildo+Calheiros&txFaseSessao=Breves+Comunica%C3%A7%C3%B5es&txTipoSessao=Ordin%C3%A1ria+-+CD&dtHoraQuarto=21%3A44 ...
... Extaíndo discurso da 14ª URL: https://www.camara.leg.br/internet/sitaqweb/TextoHTML.asp?etapa=5&nuSessao=183.2022&nuQuarto=2761691&nuOrador=1&nuInsercao=1&dtHorarioQuarto=21%3A36&sgFaseSessao=BC&Data=22%2F12%2F2022&txApelido=Bia+Kicis&txFaseSessao=Breves+Comunica%C3%A7%C3%B5es&txTipoSessao=Ordin%C3%A1ria+-+CD&dtHoraQuarto=21%3A36 ...
... Extaíndo discurso da 15ª URL: https://www.camara.leg.br/internet/sitaqweb/TextoHTML.asp?etapa=5&nuSessao=183.2022&nuQuarto=2761685&nuOrador=1&nuInsercao=1&dtHorarioQuarto=21%3A32&sgFaseSessao=BC&Data=22%2F12%2F2022&txApelido=Marcel+Van+Hattem&txFaseSessao=Breves+Comunica%C3%A7%C3%B5es&txTipoSessao=Ordin%C3%A1ria+-+CD&dtHoraQuarto=21%3A32 ...
... Extaíndo discurso da 16ª URL: https://www.camara.leg.br/internet/sitaqweb/TextoHTML.asp?etapa=5&nuSessao=183.2022&nuQuarto=2761682&nuOrador=1&nuInsercao=1&dtHorarioQuarto=21%3A28&sgFaseSessao=BC&Data=22%2F12%2F2022&txApelido=Tiago+Mitraud&txFaseSessao=Breves+Comunica%C3%A7%C3%B5es&txTipoSessao=Ordin%C3%A1ria+-+CD&dtHoraQuarto=21%3A28 ...
... Extaíndo discurso da 17ª URL: https://www.camara.leg.br/internet/sitaqweb/TextoHTML.asp?etapa=5&nuSessao=183.2022&nuQuarto=2761675&nuOrador=1&nuInsercao=1&dtHorarioQuarto=21%3A16&sgFaseSessao=BC&Data=22%2F12%2F2022&txApelido=Paulo+Ganime&txFaseSessao=Breves+Comunica%C3%A7%C3%B5es&txTipoSessao=Ordin%C3%A1ria+-+CD&dtHoraQuarto=21%3A16 ...
... Extaíndo discurso da 18ª URL: https://www.camara.leg.br/internet/sitaqweb/TextoHTML.asp?etapa=5&nuSessao=32.2022.N&nuQuarto=2759638&nuOrador=1&nuInsercao=1&dtHorarioQuarto=11%3A12&sgFaseSessao=HO&Data=22%2F12%2F2022&txApelido=Mauro+Benevides+Filho&txFaseSessao=Homenagem&txTipoSessao=Ordin%C3%A1ria+-+CD&dtHoraQuarto=11%3A12 ...
... Extaíndo discurso da 19ª URL: https://www.camara.leg.br/internet/sitaqweb/TextoHTML.asp?etapa=5&nuSessao=32.2022.N&nuQuarto=2759633&nuOrador=1&nuInsercao=1&dtHorarioQuarto=11%3A04&sgFaseSessao=HO&Data=22%2F12%2F2022&txApelido=Carmen+Zanotto&txFaseSessao=Homenagem&txTipoSessao=Ordin%C3%A1ria+-+CD&dtHoraQuarto=11%3A04 ...
... Extaíndo discurso da 20ª URL: https://www.camara.leg.br/internet/sitaqweb/TextoHTML.asp?etapa=5&nuSessao=32.2022.N&nuQuarto=2759626&nuOrador=1&nuInsercao=1&dtHorarioQuarto=10%3A56&sgFaseSessao=HO&Data=22%2F12%2F2022&txApelido=Alice+Portugal&txFaseSessao=Homenagem&txTipoSessao=Ordin%C3%A1ria+-+CD&dtHoraQuarto=10%3A56 ...
... Extaíndo discurso da 21ª URL: https://www.camara.leg.br/internet/sitaqweb/TextoHTML.asp?etapa=5&nuSessao=183.2022&nuQuarto=2761780&nuOrador=1&nuInsercao=1&dtHorarioQuarto=09%3A00&sgFaseSessao=EN&Data=22%2F12%2F2022&txApelido=Luiz+Lima&txFaseSessao=Encerramento&txTipoSessao=Ordin%C3%A1ria+-+CD&dtHoraQuarto=09%3A00 ...
... Extaíndo discurso da 22ª URL: https://www.camara.leg.br/internet/sitaqweb/TextoHTML.asp?etapa=5&nuSessao=183.2022&nuQuarto=2761779&nuOrador=1&nuInsercao=1&dtHorarioQuarto=09%3A00&sgFaseSessao=EN&Data=22%2F12%2F2022&txApelido=Aline+Gurgel&txFaseSessao=Encerramento&txTipoSessao=Ordin%C3%A1ria+-+CD&dtHoraQuarto=09%3A00 ...
... Extaíndo discurso da 23ª URL: https://www.camara.leg.br/internet/sitaqweb/TextoHTML.asp?etapa=5&nuSessao=182.2022&nuQuarto=2761511&nuOrador=1&nuInsercao=1&dtHorarioQuarto=23%3A08&sgFaseSessao=OD&Data=21%2F12%2F2022&txApelido=Jo%C3%A3o+Campos&txFaseSessao=Ordem+do+Dia&txTipoSessao=Ordin%C3%A1ria+-+CD&dtHoraQuarto=23%3A08 ...
... Extaíndo discurso da 24ª URL: https://www.camara.leg.br/internet/sitaqweb/TextoHTML.asp?etapa=5&nuSessao=182.2022&nuQuarto=2761426&nuOrador=1&nuInsercao=1&dtHorarioQuarto=23%3A00&sgFaseSessao=OD&Data=21%2F12%2F2022&txApelido=Tiago+Mitraud&txFaseSessao=Ordem+do+Dia&txTipoSessao=Ordin%C3%A1ria+-+CD&dtHoraQuarto=23%3A00 ...
... Extaíndo discurso da 25ª URL: https://www.camara.leg.br/internet/sitaqweb/TextoHTML.asp?etapa=5&nuSessao=182.2022&nuQuarto=2761430&nuOrador=1&nuInsercao=1&dtHorarioQuarto=23%3A00&sgFaseSessao=OD&Data=21%2F12%2F2022&txApelido=Jo%C3%A3o+Campos&txFaseSessao=Ordem+do+Dia&txTipoSessao=Ordin%C3%A1ria+-+CD&dtHoraQuarto=23%3A00 ...
... Extaíndo discurso da 26ª URL: https://www.camara.leg.br/internet/sitaqweb/TextoHTML.asp?etapa=5&nuSessao=182.2022&nuQuarto=2761424&nuOrador=1&nuInsercao=1&dtHorarioQuarto=23%3A00&sgFaseSessao=OD&Data=21%2F12%2F2022&txApelido=Erika+Kokay&txFaseSessao=Ordem+do+Dia&txTipoSessao=Ordin%C3%A1ria+-+CD&dtHoraQuarto=23%3A00 ...
... Extaíndo discurso da 27ª URL: https://www.camara.leg.br/internet/sitaqweb/TextoHTML.asp?etapa=5&nuSessao=182.2022&nuQuarto=2761415&nuOrador=1&nuInsercao=1&dtHorarioQuarto=22%3A56&sgFaseSessao=OD&Data=21%2F12%2F2022&txApelido=Erika+Kokay&txFaseSessao=Ordem+do+Dia&txTipoSessao=Ordin%C3%A1ria+-+CD&dtHoraQuarto=22%3A56 ...
... Extaíndo discurso da 28ª URL: https://www.camara.leg.br/internet/sitaqweb/TextoHTML.asp?etapa=5&nuSessao=182.2022&nuQuarto=2761417&nuOrador=1&nuInsercao=1&dtHorarioQuarto=22%3A56&sgFaseSessao=OD&Data=21%2F12%2F2022&txApelido=Bia+Kicis&txFaseSessao=Ordem+do+Dia&txTipoSessao=Ordin%C3%A1ria+-+CD&dtHoraQuarto=22%3A56 ...
... Extaíndo discurso da 29ª URL: https://www.camara.leg.br/internet/sitaqweb/TextoHTML.asp?etapa=5&nuSessao=182.2022&nuQuarto=2761592&nuOrador=1&nuInsercao=1&dtHorarioQuarto=22%3A52&sgFaseSessao=OD&Data=21%2F12%2F2022&txApelido=Bia+Kicis&txFaseSessao=Ordem+do+Dia&txTipoSessao=Ordin%C3%A1ria+-+CD&dtHoraQuarto=22%3A52 ...
... Extaíndo discurso da 30ª URL: https://www.camara.leg.br/internet/sitaqweb/TextoHTML.asp?etapa=5&nuSessao=182.2022&nuQuarto=2761586&nuOrador=1&nuInsercao=1&dtHorarioQuarto=22%3A48&sgFaseSessao=OD&Data=21%2F12%2F2022&txApelido=Jo%C3%A3o+Campos&txFaseSessao=Ordem+do+Dia&txTipoSessao=Ordin%C3%A1ria+-+CD&dtHoraQuarto=22%3A48 ...
... Extaíndo discurso da 31ª URL: https://www.camara.leg.br/internet/sitaqweb/TextoHTML.asp?etapa=5&nuSessao=182.2022&nuQuarto=2761584&nuOrador=1&nuInsercao=1&dtHorarioQuarto=22%3A48&sgFaseSessao=OD&Data=21%2F12%2F2022&txApelido=Erika+Kokay&txFaseSessao=Ordem+do+Dia&txTipoSessao=Ordin%C3%A1ria+-+CD&dtHoraQuarto=22%3A48 ...
... Extaíndo discurso da 32ª URL: https://www.camara.leg.br/internet/sitaqweb/TextoHTML.asp?etapa=5&nuSessao=182.2022&nuQuarto=2761581&nuOrador=1&nuInsercao=1&dtHorarioQuarto=22%3A48&sgFaseSessao=OD&Data=21%2F12%2F2022&txApelido=Bia+Kicis&txFaseSessao=Ordem+do+Dia&txTipoSessao=Ordin%C3%A1ria+-+CD&dtHoraQuarto=22%3A48 ...
... Extaíndo discurso da 33ª URL: https://www.camara.leg.br/internet/sitaqweb/TextoHTML.asp?etapa=5&nuSessao=182.2022&nuQuarto=2761575&nuOrador=1&nuInsercao=1&dtHorarioQuarto=22%3A40&sgFaseSessao=OD&Data=21%2F12%2F2022&txApelido=Professor+Israel+Batista&txFaseSessao=Ordem+do+Dia&txTipoSessao=Ordin%C3%A1ria+-+CD&dtHoraQuarto=22%3A40 ...
... Extaíndo discurso da 34ª URL: https://www.camara.leg.br/internet/sitaqweb/TextoHTML.asp?etapa=5&nuSessao=182.2022&nuQuarto=2761568&nuOrador=1&nuInsercao=1&dtHorarioQuarto=22%3A40&sgFaseSessao=OD&Data=21%2F12%2F2022&txApelido=Jo%C3%A3o+Campos&txFaseSessao=Ordem+do+Dia&txTipoSessao=Ordin%C3%A1ria+-+CD&dtHoraQuarto=22%3A40 ...
... Extaíndo discurso da 35ª URL: https://www.camara.leg.br/internet/sitaqweb/TextoHTML.asp?etapa=5&nuSessao=182.2022&nuQuarto=2761574&nuOrador=1&nuInsercao=1&dtHorarioQuarto=22%3A40&sgFaseSessao=OD&Data=21%2F12%2F2022&txApelido=Erika+Kokay&txFaseSessao=Ordem+do+Dia&txTipoSessao=Ordin%C3%A1ria+-+CD&dtHoraQuarto=22%3A40 ...
... Extaíndo discurso da 36ª URL: https://www.camara.leg.br/internet/sitaqweb/TextoHTML.asp?etapa=5&nuSessao=182.2022&nuQuarto=2760799&nuOrador=1&nuInsercao=1&dtHorarioQuarto=22%3A32&sgFaseSessao=OD&Data=21%2F12%2F2022&txApelido=Liziane+Bayer&txFaseSessao=Ordem+do+Dia&txTipoSessao=Ordin%C3%A1ria+-+CD&dtHoraQuarto=22%3A32 ...
... Extaíndo discurso da 37ª URL: https://www.camara.leg.br/internet/sitaqweb/TextoHTML.asp?etapa=5&nuSessao=182.2022&nuQuarto=2760792&nuOrador=1&nuInsercao=1&dtHorarioQuarto=22%3A28&sgFaseSessao=OD&Data=21%2F12%2F2022&txApelido=Erika+Kokay&txFaseSessao=Ordem+do+Dia&txTipoSessao=Ordin%C3%A1ria+-+CD&dtHoraQuarto=22%3A28 ...
... Extaíndo discurso da 38ª URL: https://www.camara.leg.br/internet/sitaqweb/TextoHTML.asp?etapa=5&nuSessao=182.2022&nuQuarto=2760794&nuOrador=1&nuInsercao=1&dtHorarioQuarto=22%3A28&sgFaseSessao=OD&Data=21%2F12%2F2022&txApelido=Bia+Kicis&txFaseSessao=Ordem+do+Dia&txTipoSessao=Ordin%C3%A1ria+-+CD&dtHoraQuarto=22%3A28 ...
... Extaíndo discurso da 39ª URL: https://www.camara.leg.br/internet/sitaqweb/TextoHTML.asp?etapa=5&nuSessao=182.2022&nuQuarto=2760781&nuOrador=1&nuInsercao=1&dtHorarioQuarto=22%3A20&sgFaseSessao=OD&Data=21%2F12%2F2022&txApelido=Z%C3%A9+Silva&txFaseSessao=Ordem+do+Dia&txTipoSessao=Ordin%C3%A1ria+-+CD&dtHoraQuarto=22%3A20 ...
... Extaíndo discurso da 40ª URL: https://www.camara.leg.br/internet/sitaqweb/TextoHTML.asp?etapa=5&nuSessao=182.2022&nuQuarto=2760768&nuOrador=1&nuInsercao=1&dtHorarioQuarto=22%3A16&sgFaseSessao=OD&Data=21%2F12%2F2022&txApelido=Z%C3%A9+Silva&txFaseSessao=Ordem+do+Dia&txTipoSessao=Ordin%C3%A1ria+-+CD&dtHoraQuarto=22%3A16 ...
... Extaíndo discurso da 41ª URL: https://www.camara.leg.br/internet/sitaqweb/TextoHTML.asp?etapa=5&nuSessao=182.2022&nuQuarto=2760772&nuOrador=1&nuInsercao=1&dtHorarioQuarto=22%3A16&sgFaseSessao=OD&Data=21%2F12%2F2022&txApelido=Tiago+Mitraud&txFaseSessao=Ordem+do+Dia&txTipoSessao=Ordin%C3%A1ria+-+CD&dtHoraQuarto=22%3A16 ...
... Extaíndo discurso da 42ª URL: https://www.camara.leg.br/internet/sitaqweb/TextoHTML.asp?etapa=5&nuSessao=182.2022&nuQuarto=2760770&nuOrador=1&nuInsercao=1&dtHorarioQuarto=22%3A16&sgFaseSessao=OD&Data=21%2F12%2F2022&txApelido=Jo%C3%A3o+Campos&txFaseSessao=Ordem+do+Dia&txTipoSessao=Ordin%C3%A1ria+-+CD&dtHoraQuarto=22%3A16 ...
... Extaíndo discurso da 43ª URL: https://www.camara.leg.br/internet/sitaqweb/TextoHTML.asp?etapa=5&nuSessao=182.2022&nuQuarto=2761549&nuOrador=1&nuInsercao=1&dtHorarioQuarto=22%3A04&sgFaseSessao=OD&Data=21%2F12%2F2022&txApelido=Tiago+Mitraud&txFaseSessao=Ordem+do+Dia&txTipoSessao=Ordin%C3%A1ria+-+CD&dtHoraQuarto=22%3A04 ...
... Extaíndo discurso da 44ª URL: https://www.camara.leg.br/internet/sitaqweb/TextoHTML.asp?etapa=5&nuSessao=182.2022&nuQuarto=2761542&nuOrador=1&nuInsercao=1&dtHorarioQuarto=22%3A00&sgFaseSessao=OD&Data=21%2F12%2F2022&txApelido=Felipe+Rigoni&txFaseSessao=Ordem+do+Dia&txTipoSessao=Ordin%C3%A1ria+-+CD&dtHoraQuarto=22%3A00 ...
... Extaíndo discurso da 45ª URL: https://www.camara.leg.br/internet/sitaqweb/TextoHTML.asp?etapa=5&nuSessao=182.2022&nuQuarto=2761543&nuOrador=1&nuInsercao=1&dtHorarioQuarto=22%3A00&sgFaseSessao=OD&Data=21%2F12%2F2022&txApelido=Eduardo+Bismarck&txFaseSessao=Ordem+do+Dia&txTipoSessao=Ordin%C3%A1ria+-+CD&dtHoraQuarto=22%3A00 ...
... Extaíndo discurso da 46ª URL: https://www.camara.leg.br/internet/sitaqweb/TextoHTML.asp?etapa=5&nuSessao=182.2022&nuQuarto=2761537&nuOrador=1&nuInsercao=1&dtHorarioQuarto=21%3A56&sgFaseSessao=OD&Data=21%2F12%2F2022&txApelido=Paulo+Ganime&txFaseSessao=Ordem+do+Dia&txTipoSessao=Ordin%C3%A1ria+-+CD&dtHoraQuarto=21%3A56 ...
... Extaíndo discurso da 47ª URL: https://www.camara.leg.br/internet/sitaqweb/TextoHTML.asp?etapa=5&nuSessao=182.2022&nuQuarto=2761539&nuOrador=1&nuInsercao=1&dtHorarioQuarto=21%3A56&sgFaseSessao=OD&Data=21%2F12%2F2022&txApelido=General+Peternelli&txFaseSessao=Ordem+do+Dia&txTipoSessao=Ordin%C3%A1ria+-+CD&dtHoraQuarto=21%3A56 ...
... Extaíndo discurso da 48ª URL: https://www.camara.leg.br/internet/sitaqweb/TextoHTML.asp?etapa=5&nuSessao=182.2022&nuQuarto=2761529&nuOrador=1&nuInsercao=1&dtHorarioQuarto=21%3A52&sgFaseSessao=OD&Data=21%2F12%2F2022&txApelido=General+Peternelli&txFaseSessao=Ordem+do+Dia&txTipoSessao=Ordin%C3%A1ria+-+CD&dtHoraQuarto=21%3A52 ...
... Extaíndo discurso da 49ª URL: https://www.camara.leg.br/internet/sitaqweb/TextoHTML.asp?etapa=5&nuSessao=182.2022&nuQuarto=2761126&nuOrador=1&nuInsercao=1&dtHorarioQuarto=21%3A48&sgFaseSessao=OD&Data=21%2F12%2F2022&txApelido=Tiago+Mitraud&txFaseSessao=Ordem+do+Dia&txTipoSessao=Ordin%C3%A1ria+-+CD&dtHoraQuarto=21%3A48 ...
... Extaíndo discurso da 50ª URL: https://www.camara.leg.br/internet/sitaqweb/TextoHTML.asp?etapa=5&nuSessao=182.2022&nuQuarto=2761124&nuOrador=1&nuInsercao=1&dtHorarioQuarto=21%3A48&sgFaseSessao=OD&Data=21%2F12%2F2022&txApelido=Erika+Kokay&txFaseSessao=Ordem+do+Dia&txTipoSessao=Ordin%C3%A1ria+-+CD&dtHoraQuarto=21%3A48 ...
... Extaíndo discurso da 51ª URL: https://www.camara.leg.br/internet/sitaqweb/TextoHTML.asp?etapa=5&nuSessao=182.2022&nuQuarto=2761110&nuOrador=1&nuInsercao=1&dtHorarioQuarto=21%3A44&sgFaseSessao=OD&Data=21%2F12%2F2022&txApelido=Jo%C3%A3o+Campos&txFaseSessao=Ordem+do+Dia&txTipoSessao=Ordin%C3%A1ria+-+CD&dtHoraQuarto=21%3A44 ...
... Extaíndo discurso da 52ª URL: https://www.camara.leg.br/internet/sitaqweb/TextoHTML.asp?etapa=5&nuSessao=182.2022&nuQuarto=2761120&nuOrador=1&nuInsercao=1&dtHorarioQuarto=21%3A44&sgFaseSessao=OD&Data=21%2F12%2F2022&txApelido=Felipe+Rigoni&txFaseSessao=Ordem+do+Dia&txTipoSessao=Ordin%C3%A1ria+-+CD&dtHoraQuarto=21%3A44 ...
... Extaíndo discurso da 53ª URL: https://www.camara.leg.br/internet/sitaqweb/TextoHTML.asp?etapa=5&nuSessao=182.2022&nuQuarto=2761117&nuOrador=1&nuInsercao=1&dtHorarioQuarto=21%3A44&sgFaseSessao=OD&Data=21%2F12%2F2022&txApelido=Erika+Kokay&txFaseSessao=Ordem+do+Dia&txTipoSessao=Ordin%C3%A1ria+-+CD&dtHoraQuarto=21%3A44 ...
... Extaíndo discurso da 54ª URL: https://www.camara.leg.br/internet/sitaqweb/TextoHTML.asp?etapa=5&nuSessao=182.2022&nuQuarto=2761114&nuOrador=1&nuInsercao=1&dtHorarioQuarto=21%3A44&sgFaseSessao=OD&Data=21%2F12%2F2022&txApelido=Bia+Kicis&txFaseSessao=Ordem+do+Dia&txTipoSessao=Ordin%C3%A1ria+-+CD&dtHoraQuarto=21%3A44 ...
... Extaíndo discurso da 55ª URL: https://www.camara.leg.br/internet/sitaqweb/TextoHTML.asp?etapa=5&nuSessao=182.2022&nuQuarto=2761104&nuOrador=1&nuInsercao=1&dtHorarioQuarto=21%3A40&sgFaseSessao=OD&Data=21%2F12%2F2022&txApelido=Felipe+Rigoni&txFaseSessao=Ordem+do+Dia&txTipoSessao=Ordin%C3%A1ria+-+CD&dtHoraQuarto=21%3A40 ...
... Extaíndo discurso da 56ª URL: https://www.camara.leg.br/internet/sitaqweb/TextoHTML.asp?etapa=5&nuSessao=182.2022&nuQuarto=2761106&nuOrador=1&nuInsercao=1&dtHorarioQuarto=21%3A40&sgFaseSessao=OD&Data=21%2F12%2F2022&txApelido=Erika+Kokay&txFaseSessao=Ordem+do+Dia&txTipoSessao=Ordin%C3%A1ria+-+CD&dtHoraQuarto=21%3A40 ...
... Extaíndo discurso da 57ª URL: https://www.camara.leg.br/internet/sitaqweb/TextoHTML.asp?etapa=5&nuSessao=182.2022&nuQuarto=2761096&nuOrador=1&nuInsercao=1&dtHorarioQuarto=21%3A36&sgFaseSessao=OD&Data=21%2F12%2F2022&txApelido=S%C3%A2mia+Bomfim&txFaseSessao=Ordem+do+Dia&txTipoSessao=Ordin%C3%A1ria+-+CD&dtHoraQuarto=21%3A36 ...

## Testes para avaliação do threshold do parsing semântico

In [ ]:
# Teste com discursos reais do CSV para ajustar o threshold + inspeção manual de chunks
from pathlib import Path

csv_path = Path.cwd().parent / "data" / "running_files" / "political_discourses_ini_31102022_fim_02012023.csv"
df_csv = pd.read_csv(csv_path)

# Mantém apenas discursos com texto disponível
df_csv = df_csv[df_csv["preprocess_disc"].notna()].copy()
df_csv = df_csv[df_csv["partido"].notna()].copy()

# Seleciona alguns discursos para inspeção rápida (2 por partido, até 6 no total)
sample_df = df_csv.groupby("partido", group_keys=False).head(2).head(6).copy()
print("Partidos no teste:", sorted(sample_df["partido"].astype(str).unique().tolist()))
print("Discursos no teste:", len(sample_df))

thresholds = [0.35, 0.45, 0.55]
results = []
inspection_data = {}  # guarda dados para inspeção manual por threshold

for threshold in thresholds:
    emb_df_test, emb_matrix_test, _ = generate_discourse_embeddings(
        dataframe=sample_df,
        party=None,
        text_col="raw_disc",
        similarity_threshold=threshold,
        min_sentences_per_chunk=1,
        max_sentences_per_chunk=None,
        save_files=False,
    )

    # Agrupa chunks por discurso para facilitar inspeção manual
    inspect_df = (
        emb_df_test
        .sort_values(["source_index", "chunk_id"])
        .groupby(["source_index", "partido", "parlamentar"], as_index=False)["chunk_text"]
        .apply(list)
        .rename(columns={"chunk_text": "chunks"})
    )
    inspect_df["n_chunks"] = inspect_df["chunks"].apply(len)

    inspection_data[threshold] = {
        "emb_df": emb_df_test,
        "emb_matrix": emb_matrix_test,
        "inspect_df": inspect_df,
    }

    results.append({
        "threshold": threshold,
        "chunks_total": len(emb_df_test),
        "embedding_shape": emb_matrix_test.shape,
        "media_chunks_por_discurso": float(inspect_df["n_chunks"].mean()) if not inspect_df.empty else 0.0,
    })

    print("\nThreshold:", threshold)
    print("Quantidade total de chunks:", len(emb_df_test))
    print("Dimensão da matriz de embeddings:", emb_matrix_test.shape)
    display(inspect_df[["source_index", "partido", "parlamentar", "n_chunks"]])

# Resumo comparativo
results_df = pd.DataFrame(results)
display(results_df)

Partidos no teste: ['NOVO', 'PCdoB', 'PL', 'PT']
Discursos no teste: 6
...................................................
... Função generate_discourse_embeddings iniciada ...

Loading weights: 100%|██████████| 199/199 [00:00<00:00, 1500.99it/s]
BertModel LOAD REPORT from: sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

... Total de chunks gerados: 58 ...

Batches: 100%|██████████| 2/2 [00:01<00:00,  1.42it/s]

... Função generate_discourse_embeddings encerrada ...
....................................................

Threshold: 0.35
Quantidade total de chunks: 58
Dimensão da matriz de embeddings: (58, 384)

   source_index partido        parlamentar  n_chunks
0             0    NOVO  Marcel Van Hattem         3
1             1   PCdoB  Renildo Calheiros         5
2             2      PT    Reginaldo Lopes         6
3             3    NOVO  Marcel Van Hattem         5
4             4      PL          Bia Kicis        20
5             6      PT    Reginaldo Lopes        19

...................................................
... Função generate_discourse_embeddings iniciada ...

Loading weights: 100%|██████████| 199/199 [00:00<00:00, 3092.33it/s]
BertModel LOAD REPORT from: sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

... Total de chunks gerados: 91 ...

Batches: 100%|██████████| 3/3 [00:01<00:00,  1.68it/s]

... Função generate_discourse_embeddings encerrada ...
....................................................

Threshold: 0.45
Quantidade total de chunks: 91
Dimensão da matriz de embeddings: (91, 384)

   source_index partido        parlamentar  n_chunks
0             0    NOVO  Marcel Van Hattem        10
1             1   PCdoB  Renildo Calheiros        12
2             2      PT    Reginaldo Lopes         7
3             3    NOVO  Marcel Van Hattem         8
4             4      PL          Bia Kicis        26
5             6      PT    Reginaldo Lopes        28

...................................................
... Função generate_discourse_embeddings iniciada ...

Loading weights: 100%|██████████| 199/199 [00:00<00:00, 4123.83it/s]
BertModel LOAD REPORT from: sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

... Total de chunks gerados: 116 ...

Batches: 100%|██████████| 4/4 [00:01<00:00,  2.33it/s]

... Função generate_discourse_embeddings encerrada ...
....................................................

Threshold: 0.55
Quantidade total de chunks: 116
Dimensão da matriz de embeddings: (116, 384)

   source_index partido        parlamentar  n_chunks
0             0    NOVO  Marcel Van Hattem        18
1             1   PCdoB  Renildo Calheiros        15
2             2      PT    Reginaldo Lopes         8
3             3    NOVO  Marcel Van Hattem        11
4             4      PL          Bia Kicis        28
5             6      PT    Reginaldo Lopes        36

   threshold  chunks_total embedding_shape  media_chunks_por_discurso
0       0.35            58       (58, 384)                   9.666667
1       0.45            91       (91, 384)                  15.166667
2       0.55           116      (116, 384)                  19.333333

Inspeção manual para threshold: 0.45

   source_index partido        parlamentar  n_chunks
0             0    NOVO  Marcel Van Hattem        10
1             1   PCdoB  Renildo Calheiros        12
2             2      PT    Reginaldo Lopes         7
3             3    NOVO  Marcel Van Hattem         8
4             4      PL          Bia Kicis        26
5             6      PT    Reginaldo Lopes        28

Discurso selecionado:
source_index: 0
partido: NOVO
parlamentar: Marcel Van Hattem
n_chunks: 10

--- Chunk 1 ---
O SR. MARCEL VAN HATTEM (NOVO - RS. Pela ordem. Sem revisão do orador.) - Sra. Presidente, caros colegas Parlamentares, este meu discurso aqui na Câmara dos Deputados, nesta noite, talvez o último discurso desta legislatura, afinal de contas faltam apenas 6 minutos para que encerre o dia e assim também se encerre esta legislatura antes do recesso, é apenas para lembrar que fiz uma questão de ordem ao Presidente da Câmara, Deputado Arthur Lira.

--- Chunk 2 ---
Soube, por meio do Presidente, que ele já tinha a decisão lavrada para ser lida quando questionado.

--- Chunk 3 ---
Infelizmente ele não está neste momento aqui presidindo a sessão, a Deputada Bia Kicis tem feito isso com louvor, mas, obviamente, na ausência do Deputado Arthur Lira, não faço à Deputada inquirição sobre a questão de ordem em relação à instalação da CPI que trata do abuso de autoridade dos Ministros do STF e do TSE.

--- Chunk 4 ---
Parece-me muito evidente que, com a chegada do recesso, não há mais tempo para instalar, e havia uma série de CPIs à frente.

--- Chunk 5 ---
Eu quero dizer que, na nova legislatura, espero que os despachos das CPIs não sejam tão morosos. Houve uma pandemia, as Comissões permaneceram fechadas, mas nós temos sete, Deputado Renildo Calheiros — sete —, CPIs cujos despachos não foram dados pela Presidência. Não se trata apenas desta, mas sobretudo da Presidência anterior, o que prejudicou investigações sérias, que poderiam ter acontecido, de CPIs protocoladas que tinham fato determinado, como foi o caso da nossa CPI, que trata do abuso de autoridade dos Ministros do STF e do TSE, que está muito bem fundamentada. O que eu quero deixar aqui ao Plenário já muito claro é que nós colheremos novamente as assinaturas para a instalação de uma Comissão Parlamentar de Inquérito na Câmara dos Deputados. Melhor do que isso, no Senado da República há uma coleta de assinaturas também acontecendo, para que a CPI ocorra de forma mista, com Senadores e com Deputados.

--- Chunk 6 ---
Vamos pelos dois caminhos, mas tenho convicção de que o melhor caminho é o das duas Casas — isso é ainda melhor —, inclusive da CPI que eu mesmo havia proposto.

--- Chunk 7 ---
Os abusos de autoridade precisam ser investigados e precisam cessar — já deveriam ter cessado, não deveriam nem ter acontecido. Tenho convicção de que uma Comissão Parlamentar Mista de Inquérito de Senadores e de Deputados vai pôr termo, vai pôr fim aos abusos de autoridade que estamos vendo dos Ministros das Supremas Cortes, tanto do Tribunal Federal quanto da Corte Eleitoral.

--- Chunk 8 ---
E é nosso papel, de Deputados e de Senadores, tomarmos essa iniciativa. Cabe ao Congresso Nacional recolocar o Supremo Tribunal Federal dentro da Constituição e fazer com que o equilíbrio entre os Poderes seja restabelecido e a harmonia reine entre nós.

--- Chunk 9 ---
Muito obrigado, Sra.

--- Chunk 10 ---
Presidente.

In [7]:
results_df

   threshold  chunks embedding_shape
0       0.35      58       (58, 384)
1       0.45      91       (91, 384)
2       0.55     116      (116, 384)

In [17]:

# ============================
# INSPEÇÃO MANUAL (ajuste aqui)
# ============================
threshold_to_inspect = 0.35

inspect_df = inspection_data[threshold_to_inspect]["inspect_df"]

print("\nInspeção manual para threshold:", threshold_to_inspect)
display(inspect_df[["source_index", "partido", "parlamentar", "n_chunks"]])

# escolha um discurso da tabela acima (source_index)
source_to_inspect = int(inspect_df.iloc[5]["source_index"])
row = inspect_df[inspect_df["source_index"] == source_to_inspect].iloc[0]

print("\nDiscurso selecionado:")
print("source_index:", row["source_index"])
print("partido:", row["partido"])
print("parlamentar:", row["parlamentar"])
print("n_chunks:", row["n_chunks"])

for i, chunk in enumerate(row["chunks"], start=1):
    print(f"\n--- Chunk {i} ---")
    print(chunk)

Inspeção manual para threshold: 0.35

   source_index partido        parlamentar  n_chunks
0             0    NOVO  Marcel Van Hattem         3
1             1   PCdoB  Renildo Calheiros         5
2             2      PT    Reginaldo Lopes         6
3             3    NOVO  Marcel Van Hattem         5
4             4      PL          Bia Kicis        20
5             6      PT    Reginaldo Lopes        19

Discurso selecionado:
source_index: 6
partido: PT
parlamentar: Reginaldo Lopes
n_chunks: 19

--- Chunk 1 ---
O SR.

--- Chunk 2 ---
REGINALDO LOPES (PT - MG.

--- Chunk 3 ---
Como Líder. Sem revisão do orador.) - Vou falar como Líder do PT, Presidenta Bia Kicis. Quero cumprimentar os Deputados. Tive a oportunidade de ouvir também a despedida do Deputado conterrâneo Tiago Mitraud, que fez um excelente trabalho. Deputado, quero parabenizar V.Exa. pela dedicação ao Estado brasileiro, ao povo brasileiro. Vamos sentir sua falta aqui.

--- Chunk 4 ---
Volte sempre.

--- Chunk 5 ---
Também o Deputado Paulo Ganime despediu-se aqui hoje.

--- Chunk 6 ---
Um foi candidato ao Governo do Rio, outro foi candidato a Vice-Presidente da República.

--- Chunk 7 ---
Então, quero aqui agradecer a convivência.

--- Chunk 8 ---
Quero também dizer que esse foi um ano importante, um ano de muito trabalho na Casa, um ano em que assumi a Liderança do meu partido.

--- Chunk 9 ---
Fizemos um planejamento no início do ano e iniciamos as nossas atividades com um seminário que eu chamei de Resistência, Travessia e Esperança. Praticamente em janeiro do ano passado, pensei o mandato em três momentos. Houve o momento em que nós fizemos aqui grandes debates, fazendo a resistência ao atual Governo, para não haver retrocessos. E também organizamos depois, logo após a eleição do Presidente Lula, essa grande travessia. E tenho convicção de que, a partir do dia 1º de janeiro, nós teremos a esperança restabelecida do ponto de vista do diálogo, do ponto de vista das políticas públicas que o Presidente Lula assumiu com o povo brasileiro. Então, esses três momentos fazem parte do nosso trabalho como Líder do partido. Tive a oportunidade de conviver com todos os Líderes, num diálogo sempre muito fraterno, e também com o conjunto de Deputados e Deputadas. Tivemos, no dia de ontem, também a contribuição de diversos partidos políticos, até daqueles que ainda não compõem a base do Governo do Presidente Lula, com o voto de confiança que era necessário, sim, para se refazer o Orçamento de 2023. Infelizmente, o Orçamento de 2023 foi enviado pelo atual Governo com destinação de recursos para as diversas áreas num valor menor do que o do ano de 2022. E foi esta a compreensão da Casa, que deu o voto para uma emenda constitucional compreendendo que era fundamental fazer uma ampliação dentro da Lei do Teto de Gastos na casa de 145 bilhões de reais, primeiro, evidentemente, para cumprir a promessa dos dois candidatos à Presidência da República que chegaram ao segundo turno, tanto o Presidente Lula como o Presidente Bolsonaro. Segundo, a Casa compreendeu que era muito legítimo e importante para o Brasil atender de maneira diferenciada as famílias que têm mais crianças e permitiu que fosse honrado o compromisso do Presidente Lula que foi contratado nas urnas, no dia 30 de outubro, liberando também, com a ampliação do teto de gastos, 150 reais para cada criança menor de 6 anos — são aproximadamente 9 milhões de crianças. Eu tenho convicção de que todos que aqui defendem a eliminação das desigualdades, da extrema pobreza, compreendem que, de fato, uma maior transferência de renda para as mães que têm mais filhos é o início desse processo. É lógico que essa não é a única ação que vai fazer o rompimento do ciclo da pobreza, mas, quando o Parlamento libera mais 75 bilhões, além do Bolsa Família, para ações complementares, eu diria que uma ação extremamente importante é a ampliação da escola em tempo integral para essas crianças. Eu acho que proteger essas mães com recursos necessários para uma alimentação básica e incorporar essas crianças a uma escola em tempo integral são ações fundamentais para rompermos esse ciclo da pobreza e da extrema desigualdade.

--- Chunk 10 ---
No País, quando falamos da extrema pobreza, percebemos que ela tem cor, ela tem sexo; mulheres negras e mães solo representam 50% dessa extrema pobreza.

--- Chunk 11 ---
Então, eu acho que uma iniciativa importante para o Brasil nos próximos 4 anos, em parceria com os Governadores e com os Prefeitos, é universalizar a escola em tempo integral, pelo menos até a idade certa da alfabetização, até os 8 anos de idade.

--- Chunk 12 ---
Isso seria uma revolução.

--- Chunk 13 ---
E o Brasil tem plenas condições de fazer isso, se focarmos como prioridade do Estado brasileiro a universalização da pré-escola, da primeira infância, em tempo integral. Temos condições reais — e desejo boa sorte para o Ministro Camilo Santana, da Educação —, condições plenas de pelo menos universalizar a escola em tempo integral para as séries iniciais do ensino fundamental.

--- Chunk 14 ---
Essa emenda constitucional, na minha opinião, é que vai permitir essa possibilidade, vai permitir a abertura desse espaço orçamentário. Hoje nós votamos o Orçamento de 2023.

--- Chunk 15 ---
Desse espaço orçamentário, 12 bilhões de reais foram alocados no Ministério da Educação, com foco nas políticas educacionais. É verdade que recursos foram alocados em quase todas as etapas educacionais, mas foram 12 bilhões de reais.

--- Chunk 16 ---
É bom lembrar também que essa emenda constitucional excepcionalizou as receitas próprias e as doações para as universidades, para o meio ambiente, para a assistência social.

--- Chunk 17 ---
E temos possibilidade ainda de usar a arrecadação extraordinária de 2023 para fazermos investimentos. Eu espero que esses recursos, no montante de 23, 24 bilhões de reais, possam ser alocados primeiramente para terminarmos as 14 mil e poucas obras que estão paralisadas no Brasil, em especial nas universidades, nos institutos federais, obras de infraestrutura, obras no campo educacional. Temos quase mil creches para a primeira infância, escola em tempo integral, paralisadas. Então, nós precisamos resolver isso.

--- Chunk 18 ---
Eu acho que o Parlamento deu uma bela contribuição para o início do Governo do Presidente Lula.

--- Chunk 19 ---
Eu, como Líder da bancada do Partido dos Trabalhadores, quero agradecer a todos e a todas que participaram deste debate. Muito obrigado.

In [19]:

# ============================
# INSPEÇÃO MANUAL (ajuste aqui)
# ============================
threshold_to_inspect = 0.45

inspect_df = inspection_data[threshold_to_inspect]["inspect_df"]

print("\nInspeção manual para threshold:", threshold_to_inspect)
display(inspect_df[["source_index", "partido", "parlamentar", "n_chunks"]])

# escolha um discurso da tabela acima (source_index)
source_to_inspect = int(inspect_df.iloc[5]["source_index"])
row = inspect_df[inspect_df["source_index"] == source_to_inspect].iloc[0]

print("\nDiscurso selecionado:")
print("source_index:", row["source_index"])
print("partido:", row["partido"])
print("parlamentar:", row["parlamentar"])
print("n_chunks:", row["n_chunks"])

for i, chunk in enumerate(row["chunks"], start=1):
    print(f"\n--- Chunk {i} ---")
    print(chunk)

Inspeção manual para threshold: 0.45

   source_index partido        parlamentar  n_chunks
0             0    NOVO  Marcel Van Hattem        10
1             1   PCdoB  Renildo Calheiros        12
2             2      PT    Reginaldo Lopes         7
3             3    NOVO  Marcel Van Hattem         8
4             4      PL          Bia Kicis        26
5             6      PT    Reginaldo Lopes        28

Discurso selecionado:
source_index: 6
partido: PT
parlamentar: Reginaldo Lopes
n_chunks: 28

--- Chunk 1 ---
O SR.

--- Chunk 2 ---
REGINALDO LOPES (PT - MG.

--- Chunk 3 ---
Como Líder. Sem revisão do orador.) - Vou falar como Líder do PT, Presidenta Bia Kicis. Quero cumprimentar os Deputados. Tive a oportunidade de ouvir também a despedida do Deputado conterrâneo Tiago Mitraud, que fez um excelente trabalho. Deputado, quero parabenizar V.Exa.

--- Chunk 4 ---
pela dedicação ao Estado brasileiro, ao povo brasileiro.

--- Chunk 5 ---
Vamos sentir sua falta aqui.

--- Chunk 6 ---
Volte sempre.

--- Chunk 7 ---
Também o Deputado Paulo Ganime despediu-se aqui hoje.

--- Chunk 8 ---
Um foi candidato ao Governo do Rio, outro foi candidato a Vice-Presidente da República.

--- Chunk 9 ---
Então, quero aqui agradecer a convivência.

--- Chunk 10 ---
Quero também dizer que esse foi um ano importante, um ano de muito trabalho na Casa, um ano em que assumi a Liderança do meu partido.

--- Chunk 11 ---
Fizemos um planejamento no início do ano e iniciamos as nossas atividades com um seminário que eu chamei de Resistência, Travessia e Esperança.

--- Chunk 12 ---
Praticamente em janeiro do ano passado, pensei o mandato em três momentos.

--- Chunk 13 ---
Houve o momento em que nós fizemos aqui grandes debates, fazendo a resistência ao atual Governo, para não haver retrocessos.

--- Chunk 14 ---
E também organizamos depois, logo após a eleição do Presidente Lula, essa grande travessia. E tenho convicção de que, a partir do dia 1º de janeiro, nós teremos a esperança restabelecida do ponto de vista do diálogo, do ponto de vista das políticas públicas que o Presidente Lula assumiu com o povo brasileiro. Então, esses três momentos fazem parte do nosso trabalho como Líder do partido. Tive a oportunidade de conviver com todos os Líderes, num diálogo sempre muito fraterno, e também com o conjunto de Deputados e Deputadas. Tivemos, no dia de ontem, também a contribuição de diversos partidos políticos, até daqueles que ainda não compõem a base do Governo do Presidente Lula, com o voto de confiança que era necessário, sim, para se refazer o Orçamento de 2023.

--- Chunk 15 ---
Infelizmente, o Orçamento de 2023 foi enviado pelo atual Governo com destinação de recursos para as diversas áreas num valor menor do que o do ano de 2022.

--- Chunk 16 ---
E foi esta a compreensão da Casa, que deu o voto para uma emenda constitucional compreendendo que era fundamental fazer uma ampliação dentro da Lei do Teto de Gastos na casa de 145 bilhões de reais, primeiro, evidentemente, para cumprir a promessa dos dois candidatos à Presidência da República que chegaram ao segundo turno, tanto o Presidente Lula como o Presidente Bolsonaro. Segundo, a Casa compreendeu que era muito legítimo e importante para o Brasil atender de maneira diferenciada as famílias que têm mais crianças e permitiu que fosse honrado o compromisso do Presidente Lula que foi contratado nas urnas, no dia 30 de outubro, liberando também, com a ampliação do teto de gastos, 150 reais para cada criança menor de 6 anos — são aproximadamente 9 milhões de crianças. Eu tenho convicção de que todos que aqui defendem a eliminação das desigualdades, da extrema pobreza, compreendem que, de fato, uma maior transferência de renda para as mães que têm mais filhos é o início desse processo. É lógico que essa não é a única ação que vai fazer o rompimento do ciclo da pobreza, mas, quando o Parlamento libera mais 75 bilhões, além do Bolsa Família, para ações complementares, eu diria que uma ação extremamente importante é a ampliação da escola em tempo integral para essas crianças. Eu acho que proteger essas mães com recursos necessários para uma alimentação básica e incorporar essas crianças a uma escola em tempo integral são ações fundamentais para rompermos esse ciclo da pobreza e da extrema desigualdade. No País, quando falamos da extrema pobreza, percebemos que ela tem cor, ela tem sexo; mulheres negras e mães solo representam 50% dessa extrema pobreza. Então, eu acho que uma iniciativa importante para o Brasil nos próximos 4 anos, em parceria com os Governadores e com os Prefeitos, é universalizar a escola em tempo integral, pelo menos até a idade certa da alfabetização, até os 8 anos de idade.

--- Chunk 17 ---
Isso seria uma revolução.

--- Chunk 18 ---
E o Brasil tem plenas condições de fazer isso, se focarmos como prioridade do Estado brasileiro a universalização da pré-escola, da primeira infância, em tempo integral. Temos condições reais — e desejo boa sorte para o Ministro Camilo Santana, da Educação —, condições plenas de pelo menos universalizar a escola em tempo integral para as séries iniciais do ensino fundamental.

--- Chunk 19 ---
Essa emenda constitucional, na minha opinião, é que vai permitir essa possibilidade, vai permitir a abertura desse espaço orçamentário. Hoje nós votamos o Orçamento de 2023.

--- Chunk 20 ---
Desse espaço orçamentário, 12 bilhões de reais foram alocados no Ministério da Educação, com foco nas políticas educacionais. É verdade que recursos foram alocados em quase todas as etapas educacionais, mas foram 12 bilhões de reais.

--- Chunk 21 ---
É bom lembrar também que essa emenda constitucional excepcionalizou as receitas próprias e as doações para as universidades, para o meio ambiente, para a assistência social.

--- Chunk 22 ---
E temos possibilidade ainda de usar a arrecadação extraordinária de 2023 para fazermos investimentos.

--- Chunk 23 ---
Eu espero que esses recursos, no montante de 23, 24 bilhões de reais, possam ser alocados primeiramente para terminarmos as 14 mil e poucas obras que estão paralisadas no Brasil, em especial nas universidades, nos institutos federais, obras de infraestrutura, obras no campo educacional.

--- Chunk 24 ---
Temos quase mil creches para a primeira infância, escola em tempo integral, paralisadas.

--- Chunk 25 ---
Então, nós precisamos resolver isso.

--- Chunk 26 ---
Eu acho que o Parlamento deu uma bela contribuição para o início do Governo do Presidente Lula.

--- Chunk 27 ---
Eu, como Líder da bancada do Partido dos Trabalhadores, quero agradecer a todos e a todas que participaram deste debate.

--- Chunk 28 ---
Muito obrigado.

## Execução da geração de embeddings

In [ ]:
from pathlib import Path

# antes da eleição
csv_path_antes = Path.cwd().parent / "data" / "running_files" / "political_discourses_ini_02072022_fim_29102022.csv"

df_csv_antes = pd.read_csv(csv_path_antes)

In [ ]:
emb_df_test, emb_matrix_test, _ = generate_discourse_embeddings(
        dataframe=df_csv_antes,
        party="UNIÃO",
        text_col="preprocess_disc",
        similarity_threshold=0.35,
        min_sentences_per_chunk=1,
        max_sentences_per_chunk=None,
        save_files=True,
        source_csv_name="political_discourses_ini_02072022_fim_29102022.csv"
)

...................................................
... Função generate_discourse_embeddings iniciada ...

c:\Users\luizf\github\luizbrandi\political-discourse-analysis\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Loading weights: 100%|██████████| 199/199 [00:00<00:00, 2104.63it/s]
BertModel LOAD REPORT from: sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

... Total de chunks gerados: 117 ...

Batches: 100%|██████████| 4/4 [00:04<00:00,  1.20s/it]

... Arquivo CSV salvo em: data/running_files/embeddings\discourses_embeddings_UNIÃO_ini_02072022_fim_29102022.csv ...
... Arquivo NPY salvo em: data/running_files/embeddings\discourses_embeddings_UNIÃO_ini_02072022_fim_29102022.npy ...
... Função generate_discourse_embeddings encerrada ...
....................................................

In [6]:
# depois da eleição
csv_path_depois = Path.cwd().parent / "data" / "running_files" / "political_discourses_ini_31102022_fim_02012023.csv"
df_csv_depois = pd.read_csv(csv_path_depois)

emb_df_test, emb_matrix_test, _ = generate_discourse_embeddings(
        dataframe=df_csv_depois,
        party="UNIÃO",
        text_col="preprocess_disc",
        similarity_threshold=0.35,
        min_sentences_per_chunk=1,
        max_sentences_per_chunk=None,
        save_files=True,
        source_csv_name="political_discourses_ini_31102022_fim_02012023.csv"
)

...................................................
... Função generate_discourse_embeddings iniciada ...

Loading weights: 100%|██████████| 199/199 [00:00<00:00, 1798.42it/s]
BertModel LOAD REPORT from: sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

... Total de chunks gerados: 103 ...

Batches: 100%|██████████| 4/4 [00:04<00:00,  1.17s/it]

... Arquivo CSV salvo em: data/running_files/embeddings\discourses_embeddings_UNIÃO_ini_31102022_fim_02012023.csv ...
... Arquivo NPY salvo em: data/running_files/embeddings\discourses_embeddings_UNIÃO_ini_31102022_fim_02012023.npy ...
... Função generate_discourse_embeddings encerrada ...
....................................................